### ISSUE TITLE
安装附属插件后功能无法实现

### ISSUE THREAD

**Issue by XiaoShuaiowo** [IllTamer/infinitebot4#15]
使用的附属插件有：basic-manager-2.0 和 chat-manager-2.0

在游戏内使用类似这种格式“#main test”说话后报错：
`[19:41:28] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to InfiniteBot3 v3.2.0
java.lang.NoClassDefFoundError: com/illtamer/infinite/bot/minecraft/Bootstrap
        at com.illtamer.infinite.bot.expansion.chat.listener.Game2GroupListener.preChat(Game2GroupListener.java:86) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor501.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) ~[SimplePluginManager.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[SimplePluginManager.class:git-CatServer-1.12.2-dae70adc]
        at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1547) ~[pa.class:?]
        at catserver.server.threads.AsyncChatThread.lambda$chat$0(AsyncChatThread.java:23) ~[AsyncChatThread.class:git-CatServer-1.12.2-dae70adc]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]`

同时在群内发消息或输入cmd say test时，游戏内没有显示，并报错：
`[19:42:53] [bot-thread-0/WARN]: java.lang.reflect.InvocationTargetException
[19:42:53] [bot-thread-0/WARN]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:42:53] [bot-thread-0/WARN]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:42:53] [bot-thread-0/WARN]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:42:53] [bot-thread-0/WARN]:         at java.lang.reflect.Method.invoke(Method.java:498)
[19:42:53] [bot-thread-0/WARN]:         at com.illtamer.infinite.bot.minecraft.api.EventExecutor$Dispatcher.run(EventExecutor.java:128)
[19:42:53] [bot-thread-0/WARN]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:42:53] [bot-thread-0/WARN]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:42:53] [bot-thread-0/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:42:53] [bot-thread-0/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:42:53] [bot-thread-0/WARN]:         at java.lang.Thread.run(Thread.java:750)
[19:42:53] [bot-thread-0/WARN]: Caused by: java.lang.NoClassDefFoundError: com/illtamer/infinite/bot/minecraft/Bootstrap
[19:42:53] [bot-thread-0/WARN]:         at com.illtamer.infinite.bot.expansion.chat.listener.Group2GameListener.onGroup(Group2GameListener.java:74)
[19:42:53] [bot-thread-0/WARN]:         ... 10 more`

**Comment by XiaoShuaiowo** [comment]
使用的核心是CatServer-1.12.2-090a6ffb

**Comment by Thexiaoyuqaq** [comment]
使用3.1.7版本

**Comment by XiaoShuaiowo** [comment]
已经更改为了3.1.7版本，但是出现了这个问题
https://github.com/IllTamer/infinite-bot-3-expansion/issues/12
