### ISSUE TITLE
在waterfall调用事件出错

### ISSUE THREAD

**Issue by ABKQPO** [IllTamer/infinitebot4#16]
[03:38:12 ERROR] [com.illtamer.infinite.bot.api.config.EventHandler]: 调用事件出错
[03:38:12 ERROR]: java.lang.RuntimeException: redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
[03:38:12 ERROR]:       at com.illtamer.infinite.bot.minecraft.util.JedisUtil.option(JedisUtil.java:35)
[03:38:12 ERROR]:       at com.illtamer.infinite.bot.minecraft.util.JedisUtil.publish(JedisUtil.java:24)
[03:38:12 ERROR]:       at com.illtamer.infinite.bot.api.config.EventHandler.channelRead0(EventHandler.java:52)
[03:38:12 ERROR]:       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:38:12 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:38:12 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:38:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[03:38:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:38:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:38:12 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[03:38:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[03:38:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[03:38:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[03:38:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[03:38:12 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:38:12 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:38:12 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[03:38:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[03:38:12 ERROR]: Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
[03:38:12 ERROR]:       at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63)
[03:38:12 ERROR]:       at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
[03:38:12 ERROR]:       at redis.clients.jedis.Connection.connect(Connection.java:180)
[03:38:12 ERROR]:       at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:338)
[03:38:12 ERROR]:       at redis.clients.jedis.Connection.<init>(Connection.java:53)
[03:38:12 ERROR]:       at redis.clients.jedis.Jedis.<init>(Jedis.java:214)
[03:38:12 ERROR]:       at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:181)
[03:38:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
[03:38:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
[03:38:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
[03:38:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:34)
[03:38:12 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:373)
[03:38:12 ERROR]:       at com.illtamer.infinite.bot.minecraft.util.JedisUtil.option(JedisUtil.java:32)
[03:38:12 ERROR]:       ... 24 more
[03:38:12 ERROR]:       Suppressed: java.net.ConnectException: Connection refused: no further information
[03:38:12 ERROR]:               at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[03:38:12 ERROR]:               at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[03:38:12 ERROR]:               at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[03:38:12 ERROR]:               at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[03:38:12 ERROR]:               at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[03:38:12 ERROR]:               at java.base/java.net.Socket.connect(Socket.java:639)
[03:38:12 ERROR]:               at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73)
[03:38:12 ERROR]:               ... 36 more

**Comment by ABKQPO** [comment]
以下为启动参数
:: on start.bat
@echo off
title WaterFall
"D:\JDK17zulu\bin\java.exe" --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -Dfile.encoding=UTF-8 -Xms512M -Xmx2G -jar waterfall-1.20-536.jar
pause

**Comment by Thexiaoyuqaq** [comment]
Bungeecord（最新版本）有点问题，先用单服吧

**Comment by IllTamer** [comment]
infinitebot4.0已移除插件内对bc核心的支持，各子服间通信通过perpetua拓展事件实现，详见本仓库更新后文档。

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
